### PR TITLE
ENH: Return transform from registration methods

### PR DESCRIPTION
**Pull request by tbirdso**
Updates registration methods to return the tuple `(transform, transformed_mesh)` so that transforms may be used directly in shape analysis.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
`build-test-cxx` is missing an ITK library file after building ITK from source:
> ninja: error: 'D:/a/HASI/ITK-build/lib/ITKRegionGrowing-5.2.lib', needed by 'D:/a/HASI/ITK-build/bin/HASIHeaderTest1.exe', missing and no known rule to make it

**Review by dzenanz — COMMENTED** [review]
Maybe do a general update to RC3+, similar to https://github.com/InsightSoftwareConsortium/ITKColorNormalization/pull/24.

**Comment by tbirdso** [comment]
Remaining CTest failure is from preexisting macOS bug:
> Performing Test ITK_UNDEFINED_SYMBOLS_ALLOWED - Failed

**Review by thewtex — APPROVED** [review]
👍

**Pull request merged**
