### PR TITLE
Simplify the atlas segmentation filter

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
Mac package script does not seem to work properly:
```log
[39/40] Linking CXX shared module /Users/svc-dashboard/D/P/ITKPythonPackage/ITK-3.7-macosx_x86_64/Wrapping/Generators/Python/itk/_BoneEnhancementPython.so
[39/40] Install the project...
-- Install configuration: "Release"
-- Install component: "PythonWheelRuntimeLibraries"
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkDescoteauxEigenToMeasureImageFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkDescoteauxEigenToMeasureParameterEstimationFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkEigenToMeasureImageFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkHessianGaussianImageFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkKrcahEigenToMeasureImageFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkKrcahEigenToMeasureParameterEstimationFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkKrcahPreprocessingImageToImageFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkMaximumAbsoluteValueImageFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/itkMultiScaleHessianEnhancementImageFilterPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/Configuration/BoneEnhancementConfig.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/BoneEnhancementPython.py
-- Installing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/_BoneEnhancementPython.so
package init file '_skbuild/macosx-10.6-intel-3.7/cmake-install/itk/__init__.py' not found (or not a regular file)
```

**Comment by thewtex** [comment]
```
2020-12-29T17:29:35.6105300Z Fixing: /Users/runner/work/HASI/HASI/ITKBoneEnhancement/dist/itk_boneenhancement-0.4.0-cp39-cp39-macosx_10_9_x86_64.whl
2020-12-29T17:29:35.6206870Z ~/work/HASI/HASI
2020-12-29T17:29:35.6306440Z /Users/runner/work/_temp/b3533fdc-49c6-4e68-85b1-f5f1bd9a0fc9.sh: line 10: /Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/macpython-build-module-wheels.sh: No such file or directory
```

The CI configuration path may need to be corrected.

**Comment by thewtex** [comment]
Maybe another CI update is required?

**Comment by dzenanz** [comment]
I will merge this now, as it is an improvement. I will come back to fixing the CI later.

**Pull request merged**
